# Training proceeds in cycles, one layer at a time, 
# each layer trained for number of epochs (full set 
# of training data processed)
num_cycles:    1
num_epochs:    5
num_classes:   10

wandb:
  project:     Forward-Forward

dataset:
  batch_size:  [16, 16]
  num_workers: [0, 0]